openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/todos:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters:
        -
          in: query
          name: status
          description: 'Filter todos by status.'
          example: completed
          required: false
          schema:
            type: string
            description: 'Filter todos by status.'
            example: completed
            nullable: false
        -
          in: query
          name: search
          description: 'Search todos by title or details.'
          example: project
          required: false
          schema:
            type: string
            description: 'Search todos by title or details.'
            example: project
            nullable: false
        -
          in: query
          name: sortBy
          description: 'Sort todos by a field.'
          example: created_at
          required: false
          schema:
            type: string
            description: 'Sort todos by a field.'
            example: created_at
            nullable: false
        -
          in: query
          name: order
          description: 'Sort order. Must be one of asc or desc.'
          example: desc
          required: false
          schema:
            type: string
            description: 'Sort order. Must be one of asc or desc.'
            example: desc
            nullable: false
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      title: 'New Todo'
                      details: 'Details about the todo'
                      status: completed
                      user:
                        id: 1
                        name: 'Kennedy Owusu'
                        email: kennedy@example.com
                      created_at: '2024-12-15T12:00:00Z'
                      updated_at: '2024-12-15T12:00:00Z'
                      deleted_at: null
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        title: 'New Todo'
                        details: 'Details about the todo'
                        status: completed
                        user:
                          id: 1
                          name: 'Kennedy Owusu'
                          email: kennedy@example.com
                        created_at: '2024-12-15T12:00:00Z'
                        updated_at: '2024-12-15T12:00:00Z'
                        deleted_at: null
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        title:
                          type: string
                          example: 'New Todo'
                        details:
                          type: string
                          example: 'Details about the todo'
                        status:
                          type: string
                          example: completed
                        user:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            name:
                              type: string
                              example: 'Kennedy Owusu'
                            email:
                              type: string
                              example: kennedy@example.com
                        created_at:
                          type: string
                          example: '2024-12-15T12:00:00Z'
                        updated_at:
                          type: string
                          example: '2024-12-15T12:00:00Z'
                        deleted_at:
                          type: string
                          example: null
      tags:
        - Todos
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    title: 'Finish project'
                    details: 'Complete API implementation'
                    status: 'in progress'
                    user:
                      id: 1
                      name: 'Kennedy Owusu'
                      email: kennedy@example.com
                    created_at: '2024-12-15T12:00:00Z'
                    updated_at: '2024-12-15T12:00:00Z'
                    deleted_at: null
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      title:
                        type: string
                        example: 'Finish project'
                      details:
                        type: string
                        example: 'Complete API implementation'
                      status:
                        type: string
                        example: 'in progress'
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: 'Kennedy Owusu'
                          email:
                            type: string
                            example: kennedy@example.com
                      created_at:
                        type: string
                        example: '2024-12-15T12:00:00Z'
                      updated_at:
                        type: string
                        example: '2024-12-15T12:00:00Z'
                      deleted_at:
                        type: string
                        example: null
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'The title of the todo.'
                  example: 'Finish project'
                  nullable: false
                details:
                  type: string
                  description: 'The details of the todo.'
                  example: 'Complete API implementation'
                  nullable: true
                status:
                  type: string
                  description: 'The status of the todo. Must be one of completed, in progress, or not started.'
                  example: 'in progress'
                  nullable: false
                user_id:
                  type: integer
                  description: 'The ID of the user.'
                  example: 1
                  nullable: false
              required:
                - title
                - status
                - user_id
      security: []
  '/api/v1/todos/{todo_id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    title: 'Finish project'
                    details: 'Complete API implementation'
                    status: 'in progress'
                    user:
                      id: 1
                      name: 'Kennedy Owusu'
                      email: kennedy@example.com
                    created_at: '2024-12-15T12:00:00Z'
                    updated_at: '2024-12-15T12:00:00Z'
                    deleted_at: null
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      title:
                        type: string
                        example: 'Finish project'
                      details:
                        type: string
                        example: 'Complete API implementation'
                      status:
                        type: string
                        example: 'in progress'
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: 'Kennedy Owusu'
                          email:
                            type: string
                            example: kennedy@example.com
                      created_at:
                        type: string
                        example: '2024-12-15T12:00:00Z'
                      updated_at:
                        type: string
                        example: '2024-12-15T12:00:00Z'
                      deleted_at:
                        type: string
                        example: null
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Todo not found.'
                properties:
                  message:
                    type: string
                    example: 'Todo not found.'
      tags:
        - Todos
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    title: 'Update title'
                    details: 'Complete API implementation'
                    status: completed
                    user:
                      id: 1
                      name: 'Kennedy Owusu'
                      email: kennedy@example.com
                    created_at: '2024-12-15T12:00:00Z'
                    updated_at: '2024-12-15T12:00:00Z'
                    deleted_at: null
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      title:
                        type: string
                        example: 'Update title'
                      details:
                        type: string
                        example: 'Complete API implementation'
                      status:
                        type: string
                        example: completed
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: 'Kennedy Owusu'
                          email:
                            type: string
                            example: kennedy@example.com
                      created_at:
                        type: string
                        example: '2024-12-15T12:00:00Z'
                      updated_at:
                        type: string
                        example: '2024-12-15T12:00:00Z'
                      deleted_at:
                        type: string
                        example: null
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'The updated title of the todo.'
                  example: 'Update title'
                  nullable: false
                details:
                  type: string
                  description: ''
                  example: error
                  nullable: true
                status:
                  type: string
                  description: 'The updated status of the todo.'
                  example: completed
                  nullable: false
                user_id:
                  type: string
                  description: 'The <code>id</code> of an existing record in the users table.'
                  example: quidem
                  nullable: false
              required:
                - user_id
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Todo deleted successfully.'
                properties:
                  message:
                    type: string
                    example: 'Todo deleted successfully.'
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Todo not found.'
                properties:
                  message:
                    type: string
                    example: 'Todo not found.'
      tags:
        - Todos
      security: []
    parameters:
      -
        in: path
        name: todo_id
        description: 'The ID of the todo.'
        example: 2
        required: true
        schema:
          type: integer
      -
        in: path
        name: todo
        description: 'The ID of the todo.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Todos
    description: ''
